// src/data/degreesData.js

export const degreesData = [
  {
    id: 1,
    university: "Birla Institute of Technology & Science, Pilani",
    title: "Bachelor of Science in Computer Science",
    degreeType: "Bachelor",
    duration: "Full-time",
    fees: "INR 1.20 Lac per year",
    deadline: "January 31, 2026",
    logo: "https://upload.wikimedia.org/wikipedia/en/6/6e/BITS_Pilani-Logo.svg",
  },
  {
    id: 2,
    university: "Indian Institute of Technology Guwahati",
    title: "Bachelor of Science in Data Science & AI",
    degreeType: "Bachelor",
    duration: "Full-time",
    fees: "INR 1.20 Lac per year",
    deadline: "January 30, 2026",
    logo: "https://upload.wikimedia.org/wikipedia/en/9/9a/IIT_Guwahati_Logo.svg",
  },
  {
    id: 3,
    university: "University of Huddersfield",
    title: "BSc Data Science",
    degreeType: "Bachelor",
    duration: "Full-time",
    fees: "INR 1.20 Lac per year",
    deadline: "January 30, 2026",
    logo: "https://upload.wikimedia.org/wikipedia/en/2/2f/University_of_Huddersfield_logo.svg",
  },
  {
    id: 4,
    university: "S.P. Jain Institute of Management and Research",
    title: "PG Diploma in Management (PGDM) Online",
    degreeType: "PG Diploma",
    duration: "Full-time",
    fees: "INR 1.20 Lac per year",
    deadline: "January 10, 2026",
    logo: "https://upload.wikimedia.org/wikipedia/commons/5/57/SPJIMR_logo.svg",
  },
  {
    id: 5,
    university: "O.P. Jindal Global University",
    title: "M.A. in International Relations, Security and Strategy",
    degreeType: "Master",
    duration: "Full-time",
    fees: "INR 1.20 Lac per year",
    deadline: "March 31, 2026",
    logo: "https://upload.wikimedia.org/wikipedia/en/5/59/O.P._Jindal_Global_University_Logo.png",
  },
  {
    id: 6,
    university: "O.P. Jindal Global University",
    title: "Bachelor of Science in Psychology",
    degreeType: "Bachelor",
    duration: "Full-time",
    fees: "INR 1.20 Lac per year",
    deadline: "March 31, 2026",
    logo: "https://upload.wikimedia.org/wikipedia/en/5/59/O.P._Jindal_Global_University_Logo.png",
  },
  {
    id: 7,
    university: "O.P. Jindal Global University",
    title: "MBA in Business Analytics",
    degreeType: "Master",
    duration: "Full-time",
    fees: "INR 1.20 Lac per year",
    deadline: "January 31, 2026",
    logo: "https://upload.wikimedia.org/wikipedia/en/5/59/O.P._Jindal_Global_University_Logo.png",
  },
  {
    id: 8,
    university: "O.P. Jindal Global University",
    title: "M.A. in Public Policy",
    degreeType: "Master",
    duration: "Full-time",
    fees: "INR 1.20 Lac per year",
    deadline: "March 31, 2026",
    logo: "https://upload.wikimedia.org/wikipedia/en/5/59/O.P._Jindal_Global_University_Logo.png",
  },
  {
    id: 9,
    university: "University of London",
    title: "Bachelor of Science in Economics",
    degreeType: "Bachelor",
    duration: "Full-time",
    fees: "INR 1.20 Lac per year",
    deadline: "April 15, 2026",
    logo: "https://upload.wikimedia.org/wikipedia/en/3/3b/University_of_London_logo.svg",
  },
  {
    id: 10,
    university: "University of Essex",
    title: "MSc Artificial Intelligence",
    degreeType: "Master",
    duration: "Full-time",
    fees: "INR 1.20 Lac per year",
    deadline: "February 28, 2026",
    logo: "https://upload.wikimedia.org/wikipedia/en/8/8a/University_of_Essex_logo.svg",
  },
  {
    id: 11,
    university: "Deakin University",
    title: "Master of Business Analytics",
    degreeType: "Master",
    duration: "Full-time",
    fees: "INR 1.20 Lac per year",
    deadline: "March 20, 2026",
    logo: "https://upload.wikimedia.org/wikipedia/en/7/78/Deakin_University_logo.svg",
  },
  {
    id: 12,
    university: "Amity University",
    title: "Online MBA",
    degreeType: "Master",
    duration: "Full-time",
    fees: "INR 1.20 Lac per year",
    deadline: "April 10, 2026",
    logo: "https://upload.wikimedia.org/wikipedia/en/3/3f/Amity_University_logo.svg",
  },
];
