export const degreesData = [
  {
    id: 1,
    title: "Advanced Manufacturing Systems and Technologies MSc",
    level: "Master's",
    award: "Master's",
    subject: "Engineering",
    subSubject: "Advanced Manufacturing",
    university: "IIT Bombay",
    duration: "3 years",
    pace: "Part-time",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&auto=format&fit=crop&q=80",
    description: "Equip yourself with the skills to design, run, and manage modern advanced manufacturing systems using industry-standard engineering methods.",
    details: "This course is ideal for engineering graduates and professionals who want to transition into leadership positions in the manufacturing and industrial systems sectors. You will explore advanced manufacturing topics, CAD/CAM integration, sustainability, and automated robotics.",
    rating: 4.8,
    reviews: 24,
    fees: "£14,500 total",
    entryRequirements: "A 2:2 UK honours degree or equivalent in Engineering, Physical Sciences, or Technology."
  },
  {
    id: 2,
    title: "LLM in Energy and Environmental Law",
    level: "Master's",
    award: "Master's",
    subject: "Law",
    subSubject: "",
    university: "IISc Bangalore",
    duration: "2 years",
    pace: "Part-time",
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80",
    description: "Explore the critical legal issues surrounding energy security, climate change, and environmental sustainability on a global scale.",
    details: "Uncover the regulatory legal systems governing energy markets, international environmental agreements, policy implementations, and resource extraction limits. Ideal for law professionals, corporate consultants, and policy experts.",
    rating: 4.9,
    reviews: 42,
    fees: "£11,800 total",
    entryRequirements: "A 2:1 honours degree in Law or a relevant field with legal work experience."
  },
  {
    id: 3,
    title: "Aviation Management (Online), MSc",
    level: "Master's",
    award: "Master's",
    subject: "Business & Management",
    subSubject: "Aviation Management",
    university: "IIT Delhi",
    duration: "18 months",
    pace: "Full-time or Part-time",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&auto=format&fit=crop&q=80",
    description: "Develop strategic skills, operations management competencies, and logistics systems insights to lead in the global aviation sector.",
    details: "Our modules cover aviation safety, airport planning, fleet management, and sustainable aviation policies. Learn from world-renowned aviation practitioners and build an industry network.",
    rating: 4.7,
    reviews: 18,
    fees: "£9,200 total",
    entryRequirements: "A Bachelor's degree in any subject or significant professional experience in operations."
  },
  {
    id: 4,
    title: "BSc (Hons) Computer Science and Artificial Intelligence",
    level: "Bachelor's",
    award: "Bachelor's",
    subject: "Data Analytics",
    subSubject: "Data Science",
    university: "IIT Madras",
    duration: "3-6 years",
    pace: "Part-time",
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&auto=format&fit=crop&q=80",
    description: "Master modern computing systems, database design, software engineering, algorithms, and deep learning models to build the future of AI.",
    details: "Created by leading academic scientists at Goldsmiths, this degree prepares you for cutting-edge roles in machine learning engineering, data analytics, and full-stack software development.",
    rating: 4.6,
    reviews: 31,
    fees: "£18,000 total",
    entryRequirements: "A-levels or equivalent qualification, with strong mathematics proficiency."
  },
  {
    id: 5,
    title: "Master of Business Administration (MBA)",
    level: "MBA",
    award: "MBA",
    subject: "Business & Management",
    subSubject: "MBA Essentials",
    university: "BITS Pilani",
    duration: "2 years",
    pace: "Part-time",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&auto=format&fit=crop&q=80",
    description: "Gain a world-class strategic business education, networking with top global leaders and learning advanced management frameworks.",
    details: "Acquire high-demand skills in financial modeling, corporate governance, digital transformation strategies, and organizational behavioral psychology.",
    rating: 4.9,
    reviews: 87,
    fees: "£16,200 total",
    entryRequirements: "A minimum of 2 years professional managerial experience alongside a UK Honours degree."
  },
  {
    id: 6,
    title: "MSc in Global Health Policy and Management",
    level: "Master's",
    award: "Master's",
    subject: "Healthcare",
    subSubject: "Global Health Policy",
    university: "University of Delhi",
    duration: "2 years",
    pace: "Part-time",
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&auto=format&fit=crop&q=80",
    description: "Understand global health systems, health economics, epidemiological trends, and design effective public health policy interventions.",
    details: "Taught by leading healthcare researchers, this course provides analytical frameworks for addressing worldwide health inequities, virus outbreaks, and healthcare delivery networks.",
    rating: 4.8,
    reviews: 15,
    fees: "£12,000 total",
    entryRequirements: "A 2:1 degree in health sciences, sociology, business, or economics."
  },
  {
    id: 7,
    title: "Certificate of Higher Education in Healthcare Management",
    level: "Certificate of Higher Education",
    award: "Certificate of Higher Education",
    subject: "Healthcare",
    subSubject: "Healthcare Management",
    university: "IIT Delhi",
    duration: "1 year",
    pace: "Part-time",
    image: "https://images.unsplash.com/photo-1516549655169-df83a0774514?w=600&auto=format&fit=crop&q=80",
    description: "Begin your healthcare leadership career with this comprehensive foundation in healthcare management and governance.",
    details: "This course establishes the key theories and practical skills needed for team supervision, budgeting, auditing, and compliance within medical clinics and hospitals.",
    rating: 4.5,
    reviews: 9,
    fees: "£4,200 total",
    entryRequirements: "High school completion or equivalent, plus basic employment in support services."
  },
  {
    id: 8,
    title: "Diploma of Higher Education in Engineering Science",
    level: "Diploma of Higher Education",
    award: "Diploma of Higher Education",
    subject: "Engineering",
    subSubject: "Engineering Science",
    university: "IIT Bombay",
    duration: "2 years",
    pace: "Part-time",
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=600&auto=format&fit=crop&q=80",
    description: "Acquire basic engineering principles and scientific tools to solve complex technology, infrastructure, and building challenges.",
    details: "Study modules in thermodynamics, materials engineering, structural design, and basic algorithms. Provides a fast track to full BSc/BEng degrees.",
    rating: 4.6,
    reviews: 12,
    fees: "£8,400 total",
    entryRequirements: "STEM A-levels or relevant level 3 college certificate in engineering."
  },
  {
    id: 9,
    title: "BSc Business and Management",
    level: "Bachelor's",
    award: "Bachelor's",
    subject: "Business & Management",
    subSubject: "Strategic Management",
    university: "IIT Madras",
    duration: "3-4 years",
    pace: "Part-time",
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600&auto=format&fit=crop&q=80",
    description: "Study key managerial concepts, marketing principles, accounting, and develop the analytical skills required to run businesses.",
    details: "A comprehensive undergraduate program developed under the guidance of the London School of Economics (LSE), offering unmatched international recognition.",
    rating: 4.7,
    reviews: 29,
    fees: "£13,800 total",
    entryRequirements: "A levels, International Baccalaureate or standard college foundation year."
  },
  {
    id: 10,
    title: "BSc (Hons) in Accounting and Financial Management",
    level: "Bachelor's",
    award: "Bachelor's",
    subject: "Accounting and Finance",
    subSubject: "Accounting",
    university: "IIT Delhi",
    duration: "3 years",
    pace: "Part-time",
    image: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80",
    description: "Launch your career in accounting with a solid grounding in financial reporting, auditing, and corporate finance laws.",
    details: "This undergraduate degree is designed to align with professional accounting body requirements, fast-tracking your status as a chartered accountant.",
    rating: 4.6,
    reviews: 14,
    fees: "£13,500 total",
    entryRequirements: "High school completion or equivalent with proficiency in arithmetic and math."
  },
  {
    id: 11,
    title: "MSc Corporate Tax Law and Auditing Standards",
    level: "Master's",
    award: "Master's",
    subject: "Accounting and Finance",
    subSubject: "Audit & Taxation",
    university: "University of Delhi",
    duration: "2 years",
    pace: "Part-time",
    image: "https://images.unsplash.com/photo-1450133064473-71024230f91b?w=600&auto=format&fit=crop&q=80",
    description: "Develop professional competence in national and international corporate tax systems and statutory audit methodologies.",
    details: "Perfect for financial compliance officers and senior tax consultants looking to master risk evaluation, ethics, and forensic audit investigations.",
    rating: 4.8,
    reviews: 21,
    fees: "£12,400 total",
    entryRequirements: "A 2:1 honours degree in Accounting, Finance, or Law."
  },
  {
    id: 12,
    title: "Master in Corporate Finance and Mergers",
    level: "Master's",
    award: "Master's",
    subject: "Accounting and Finance",
    subSubject: "Corporate Finance",
    university: "IISc Bangalore",
    duration: "18 months",
    pace: "Full-time or Part-time",
    image: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=600&auto=format&fit=crop&q=80",
    description: "Master investment appraisal, risk management, and the financial frameworks governing mergers and acquisitions.",
    details: "Gain practical insights into capital structure, corporate valuation, and venture financing from leading investment banking professionals.",
    rating: 4.9,
    reviews: 35,
    fees: "£15,000 total",
    entryRequirements: "A quantitative undergraduate degree or three years of corporate finance work experience."
  },
  {
    id: 13,
    title: "BA (Hons) Modern World History",
    level: "Bachelor's",
    award: "Bachelor's",
    subject: "Arts and Humanities",
    subSubject: "History",
    university: "IIT Madras",
    duration: "3-6 years",
    pace: "Part-time",
    image: "https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=600&auto=format&fit=crop&q=80",
    description: "Explore the events, ideologies, and structural shifts that shaped modern civilisations from the Renaissance to the digital era.",
    details: "Engage with historical archives, research methodologies, and global historiography to cultivate critical analysis and research capabilities.",
    rating: 4.7,
    reviews: 29,
    fees: "£12,000 total",
    entryRequirements: "A-levels or international equivalent, with strong writing and analytical skills."
  },
  {
    id: 14,
    title: "MA English Literature and Creative Analysis",
    level: "Master's",
    award: "Master's",
    subject: "Arts and Humanities",
    subSubject: "Literature",
    university: "University of Delhi",
    duration: "2 years",
    pace: "Part-time",
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
    description: "Study key texts across historical literary epochs, cultivating advanced analytical skills and deep critical reading capabilities.",
    details: "Explore critical theory, post-colonial literature, Shakespearean studies, and contemporary novels, preparing you for PhD pathways or writing careers.",
    rating: 4.8,
    reviews: 19,
    fees: "£9,800 total",
    entryRequirements: "A 2:1 honours degree in English Literature or a closely related humanities field."
  },
  {
    id: 15,
    title: "BA (Hons) Creative Writing and Publishing",
    level: "Bachelor's",
    award: "Bachelor's",
    subject: "Arts and Humanities",
    subSubject: "Creative Writing",
    university: "IIT Delhi",
    duration: "3 years",
    pace: "Part-time",
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=600&auto=format&fit=crop&q=80",
    description: "Nurture your voice across fiction, poetry, and scriptwriting, whilst developing practical skills in editing and digital publishing.",
    details: "Participate in collaborative peer workshops, pitch to publishing houses, and build a diverse portfolio under the guidance of published novelists.",
    rating: 4.5,
    reviews: 22,
    fees: "£11,200 total",
    entryRequirements: "High school completion and a portfolio submission of creative writing samples."
  },
  {
    id: 16,
    title: "MSc Big Data Systems and Distributed Infrastructure",
    level: "Master's",
    award: "Master's",
    subject: "Data Analytics",
    subSubject: "Big Data",
    university: "IIT Bombay",
    duration: "2 years",
    pace: "Part-time",
    image: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=600&auto=format&fit=crop&q=80",
    description: "Design and implement scalable distributed systems capable of storing, processing, and analyzing petabyte-scale data streams.",
    details: "Focus on Hadoop ecosystems, Spark stream processing, distributed databases (NoSQL), cloud microservices, and network hardware parameters.",
    rating: 4.8,
    reviews: 16,
    fees: "£14,800 total",
    entryRequirements: "A Bachelor's degree in Computer Science, Software Engineering, or Mathematics."
  },
  {
    id: 17,
    title: "MSc Data Engineering and Cloud Architecture",
    level: "Master's",
    award: "Master's",
    subject: "Data Analytics",
    subSubject: "Data Engineering",
    university: "BITS Pilani",
    duration: "2 years",
    pace: "Part-time",
    image: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=600&auto=format&fit=crop&q=80",
    description: "Build robust data pipelines, orchestrate ETL workflows, and deploy enterprise database solutions in AWS, Azure, and GCP.",
    details: "Equip yourself with data warehousing skills, streaming frameworks (Kafka), API architectures, and pipeline monitoring capabilities.",
    rating: 4.7,
    reviews: 33,
    fees: "£13,900 total",
    entryRequirements: "A degree in computing or software, or professional software engineering credentials."
  },
  {
    id: 18,
    title: "BSc Information Systems and Data Management",
    level: "Bachelor's",
    award: "Bachelor's",
    subject: "Data Analytics",
    subSubject: "Data Management",
    university: "IIT Madras",
    duration: "3-4 years",
    pace: "Part-time",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&auto=format&fit=crop&q=80",
    description: "Study how modern businesses govern, organize, protect, and distribute their vital digital data assets.",
    details: "Covers database modeling, SQL scripting, data governance standards, GDPR compliance, cybersecurity protocols, and business intelligence reporting.",
    rating: 4.6,
    reviews: 27,
    fees: "£16,000 total",
    entryRequirements: "Standard high school entry qualifications with a strong personal statement."
  },
  {
    id: 19,
    title: "MSc Data Mining and Knowledge Discovery",
    level: "Master's",
    award: "Master's",
    subject: "Data Analytics",
    subSubject: "Data Mining",
    university: "IIT Bombay",
    duration: "18 months",
    pace: "Part-time",
    image: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=600&auto=format&fit=crop&q=80",
    description: "Extract hidden patterns, correlations, and intelligence from extremely large, complex datasets using advanced algorithmic techniques.",
    details: "Incorporate classification, clustering, association rule mining, anomaly detection, and predictive statistics using Python and R ecosystems.",
    rating: 4.7,
    reviews: 13,
    fees: "£13,200 total",
    entryRequirements: "A Bachelor's degree with a high math/statistical component."
  },
  {
    id: 20,
    title: "MSc Data Journalism and Visualisation",
    level: "Master's",
    award: "Master's",
    subject: "Data Analytics",
    subSubject: "Data Visualisation",
    university: "IIT Delhi",
    duration: "2 years",
    pace: "Part-time",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&auto=format&fit=crop&q=80",
    description: "Translate complex numbers and database analytics into compelling visual stories, charts, and interactive infographics.",
    details: "Covers front-end visual libraries (D3.js, Chart.js), dashboard design (Tableau), graphic assets, UI elements, and data narrative structure.",
    rating: 4.9,
    reviews: 20,
    fees: "£9,800 total",
    entryRequirements: "An undergraduate degree in computer science, statistics, design, or communications."
  },
  {
    id: 21,
    title: "MSc Civil Engineering and Infrastructure Design",
    level: "Master's",
    award: "Master's",
    subject: "Engineering",
    subSubject: "Civil Engineering",
    university: "BITS Pilani",
    duration: "2 years",
    pace: "Part-time",
    image: "https://images.unsplash.com/photo-1590069261209-f8e9b8642343?w=600&auto=format&fit=crop&q=80",
    description: "Analyze and design safe, sustainable infrastructure assets including bridges, structural systems, and water networks.",
    details: "Modules cover structural analytics, geotechnical mechanics, environmental impacts, concrete composites, and CAD modeling applications.",
    rating: 4.8,
    reviews: 30,
    fees: "£14,100 total",
    entryRequirements: "An engineering degree (BEng or BSc) in Civil Engineering or Mechanical Engineering."
  },
  {
    id: 22,
    title: "MSc Nursing Leadership and Healthcare Quality",
    level: "Master's",
    award: "Master's",
    subject: "Healthcare",
    subSubject: "Nursing Leadership",
    university: "IISc Bangalore",
    duration: "2 years",
    pace: "Part-time",
    image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=600&auto=format&fit=crop&q=80",
    description: "Empower yourself to lead clinical nursing teams, draft care pathways, and raise safety and quality standards across healthcare sectors.",
    details: "Prepare for advanced nursing officer, unit director, or manager posts by studying organizational dynamics, patient safety frameworks, and health legislation.",
    rating: 4.9,
    reviews: 47,
    fees: "£11,950 total",
    entryRequirements: "Registered nurse status with a Bachelor's degree and a minimum of 2 years clinical nursing experience."
  }
];

export const awardsList = [
  "Bachelor's",
  "Certificate of Higher Education",
  "Diploma of Higher Education",
  "Master's",
  "MBA",
  "Doctorate",
  "Associate Degree",
  "Professional Certificate"
];

export const subjectsHierarchy = [
  { name: "Accounting and Finance", subItems: ["Accounting", "Audit & Taxation", "Corporate Finance"] },
  { name: "Arts and Humanities", subItems: ["History", "Literature", "Creative Writing"] },
  { name: "Business & Management", subItems: ["Aviation Management", "Strategic Management", "MBA Essentials"] },
  { name: "Criminology" },
  { name: "Culinary Arts" },
  { name: "Data Analytics", subItems: ["Big Data", "Data Engineering", "Data Management", "Data Mining", "Data Science", "Data Visualisation"] },
  { name: "Economics" },
  { name: "Electrical Engineering" },
  { name: "Engineering", subItems: ["Advanced Manufacturing", "Engineering Science", "Civil Engineering"] },
  { name: "Environmental Science" },
  { name: "Healthcare", subItems: ["Healthcare Management", "Global Health Policy", "Nursing Leadership"] },
  { name: "Law" }
];

export const universitiesList = [
  "IIT Bombay",
  "IISc Bangalore",
  "IIT Delhi",
  "IIT Madras",
  "BITS Pilani",
  "University of Delhi"
];
